using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using LiveChartsCore;
using LiveChartsCore.SkiaSharpView;
using LiveChartsCore.SkiaSharpView.Painting;
using SkiaSharp;
using System.Collections.ObjectModel;
using System.Windows;
using SystemMonitor.Core.Models;
using SystemMonitor.WPF.Models;

namespace SystemMonitor.WPF.ViewModels;

/// <summary>
/// ViewModel for the Dashboard view. Maintains live metric values and rolling
/// history collections for the CPU line chart.
///
/// All property updates are marshalled to the UI thread inside
/// <see cref="OnSnapshotReceived"/> via <see cref="Application.Current.Dispatcher"/>.
/// </summary>
public sealed partial class DashboardViewModel : ViewModelBase
{
    private const int HistoryLength = 100; // number of data points on the chart

    // ── Observable properties (source-generated by CommunityToolkit.Mvvm) ──

    [ObservableProperty] private double _cpuPercent;
    [ObservableProperty] private long _ramUsedMb;
    [ObservableProperty] private long _ramTotalMb;
    [ObservableProperty] private double _ramPercent;
    [ObservableProperty] private long _diskUsedMb;
    [ObservableProperty] private long _diskTotalMb;
    [ObservableProperty] private double _diskPercent;
    [ObservableProperty] private string _lastUpdated = "--:--:--";
    public ObservableCollection<AlertNotification> Alerts { get; } = new();

    // ── Chart data ──────────────────────────────────────────────────────────

    private readonly ObservableCollection<double> _cpuHistory = new();
    private readonly ObservableCollection<double> _ramHistory = new();
    private readonly ObservableCollection<double> _diskHistory = new();

    public ISeries[] CpuSeries { get; }
    public ISeries[] RamSeries { get; }
    public ISeries[] DiskSeries { get; }
    public Axis[] XAxes { get; }
    public Axis[] YAxes { get; }

    public DashboardViewModel()
    {
        // Pre-fill history with zeros so the chart appears immediately
        for (int i = 0; i < HistoryLength; i++)
        {
            _cpuHistory.Add(0);
            _ramHistory.Add(0);
            _diskHistory.Add(0);
        }

        CpuSeries = new ISeries[]
        {
            new LineSeries<double>
            {
                Values        = _cpuHistory,
                Name          = "CPU %",
                Stroke        = new SolidColorPaint(SKColor.Parse("#2196F3"), 2),
                Fill          = new SolidColorPaint(SKColor.Parse("#1A2196F3")),
                GeometrySize  = 0,
                LineSmoothness= 0.5
            }
        };

        RamSeries = new ISeries[]
        {
            new LineSeries<double>
            {
                Values        = _ramHistory,
                Name          = "RAM %",
                Stroke        = new SolidColorPaint(SKColor.Parse("#4CAF50"), 2),
                Fill          = new SolidColorPaint(SKColor.Parse("#1A4CAF50")),
                GeometrySize  = 0,
                LineSmoothness= 0.5
            }
        };

        DiskSeries = new ISeries[]
        {
            new LineSeries<double>
            {
                Values        = _diskHistory,
                Name          = "Disk %",
                Stroke        = new SolidColorPaint(SKColor.Parse("#FF9800"), 2),
                Fill          = new SolidColorPaint(SKColor.Parse("#1AFF9800")),
                GeometrySize  = 0,
                LineSmoothness= 0.5
            }
        };

        YAxes = new Axis[]
        {
            new Axis
            {
                MinLimit = 0,
                MaxLimit = 100,
                Labeler  = v => $"{v:F0}%",
                TextSize = 10
            }
        };

        XAxes = new Axis[]
        {
            new Axis { Labels = null, ShowSeparatorLines = false }
        };
    }

    // ── Public API ──────────────────────────────────────────────────────────

    public void OnSnapshotReceived(SystemSnapshot snapshot)
    {
        Application.Current.Dispatcher.Invoke(() =>
        {
            CpuPercent = snapshot.CpuPercent;
            RamUsedMb = snapshot.RamUsedMb;
            RamTotalMb = snapshot.RamTotalMb;
            RamPercent = snapshot.RamPercent;
            DiskUsedMb = snapshot.DiskUsedMb;
            DiskTotalMb = snapshot.DiskTotalMb;
            DiskPercent = snapshot.DiskPercent;
            LastUpdated = snapshot.Timestamp.ToString("HH:mm:ss");

            AddHistory(_cpuHistory, snapshot.CpuPercent);
            AddHistory(_ramHistory, snapshot.RamPercent);
            AddHistory(_diskHistory, snapshot.DiskPercent);
        });
    }

    /// Shows an alert banner in the dashboard.
    public async void ShowAlert(string metric, string message)
    {
        var alert = new AlertNotification
        {
            MetricName = metric,
            Message = message
        };

        await Application.Current.Dispatcher.InvokeAsync(() =>
        {
            Alerts.Insert(0, alert);
        });

        _ = Task.Run(async () =>
        {
            await Task.Delay(5000);

            await Application.Current.Dispatcher.InvokeAsync(() =>
            {
                Alerts.Remove(alert);
            });
        });
    }

    [RelayCommand]
    private void DismissAlert(AlertNotification alert)
    {
        Alerts.Remove(alert);
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    private static void AddHistory(ObservableCollection<double> history, double value)
    {
        if (history.Count >= HistoryLength)
            history.RemoveAt(0);
        history.Add(value);
    }
}
